apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesdemo-deployment
  namespace: salesdemo
  labels:
    app: salesdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salesdemo
  template:
    metadata:
      labels:
        app: salesdemo
    spec:
      containers:
        - name: salesdemo
          image: vivekkashyap043/salesdemo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20
